"""add vendor and cost fields to complaints

Revision ID: 073de8b7e3c1
Revises: 58014653eae9
Create Date: 2026-10-10 11:47:38.400957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073de8b7e3c1'
down_revision: Union[str, Sequence[str], None] = '58014653eae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('vendor_name', sa.String(length=200), nullable=True))
    op.add_column('complaints', sa.Column('vendor_contact', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'cost')
    op.drop_column('complaints', 'vendor_contact')
    op.drop_column('complaints', 'vendor_name')
    # ### end Alembic commands ###
